<a href="https://colab.research.google.com/github/ZhiyanAbdallah/Calculator/blob/main/PYTORCH1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#CREATING A SCALAR
import torch
scalar=torch.tensor(8)
scalardim=scalar.ndim
print(f'The scalar is {scalar}')
print(f'The n dim  of the scalar is {scalardim}')

The scalar is 8
The n dim  of the scalar is 0


In [8]:
#CREATING A VECTOR
import torch
vector=torch.tensor([3,5])
vectorshape=vector.shape
vectorndim=vector.ndim
print(f'The vector is {vector}')
print(f'The vector shape is {vectorshape}')
print(f'The vector number of dimension is {vectorndim}')

The vector is tensor([3, 5])
The vector shape is torch.Size([2])
The vector number of dimension is 1


In [9]:
#CREATING A MATRIX
MATRIX=torch.tensor([[4,7],[7,9],[1,9],[6,4],[5,9]])
print(f'The matrix is {MATRIX}')
print(f'The matrix shape is {MATRIX.shape}')
print(f'The Matrix number of dimension is {MATRIX.ndim}')

The matrix is tensor([[4, 7],
        [7, 9],
        [1, 9],
        [6, 4],
        [5, 9]])
The matrix shape is torch.Size([5, 2])
The Matrix number of dimension is 2


In [11]:
#CREATING TENSORS
TENSOR=torch.tensor([[[5,8],[9,9],[8,5],[7,5],[4,7],[7,9],[1,9],[6,4],[5,9]]])
print(f'The tensor is {TENSOR}')
print(f'The tensor shape is {TENSOR.shape}')
print(f'The tensor number of dimension is {TENSOR.ndim}')

The tensor is tensor([[[5, 8],
         [9, 9],
         [8, 5],
         [7, 5],
         [4, 7],
         [7, 9],
         [1, 9],
         [6, 4],
         [5, 9]]])
The tensor shape is torch.Size([1, 9, 2])
The tensor number of dimension is 3


In [16]:
#CREATING RANDOM NUMBERS
import torch
RANDOM_TENSOR=torch.rand(9,5)
print(RANDOM_TENSOR)
print(f'The shape of this random tensor is {RANDOM_TENSOR.shape}')
print(f'The number of dimension of the tensor is {RANDOM_TENSOR.ndim}')

tensor([[3.6951e-01, 1.5289e-01, 1.1341e-01, 8.5827e-01, 9.3405e-02],
        [4.9882e-01, 9.8212e-01, 8.2759e-01, 1.7829e-01, 7.7212e-03],
        [7.1752e-01, 2.5282e-01, 9.1629e-01, 9.8414e-01, 1.5507e-01],
        [4.6440e-02, 1.1417e-01, 9.0715e-01, 5.9483e-01, 5.0256e-01],
        [3.1751e-01, 3.4498e-01, 5.6749e-01, 4.4484e-01, 5.9900e-01],
        [9.6569e-01, 2.7600e-01, 4.4711e-01, 6.6573e-01, 8.5607e-01],
        [5.5471e-01, 8.6056e-02, 8.7917e-01, 7.5314e-01, 6.3382e-01],
        [9.0804e-01, 3.4410e-01, 5.5319e-01, 7.0227e-01, 4.3589e-01],
        [8.4036e-01, 3.9822e-01, 9.8349e-02, 3.2130e-01, 9.0593e-04]])
The shape of this random tensor is torch.Size([9, 5])
The number of dimension of the tensor is 2


In [17]:
#CREATING RANDOM TENSORS OF IMAGE
img=torch.rand(size=(340,340,3))
img





tensor([[[0.6316, 0.6970, 0.0470],
         [0.2652, 0.8844, 0.7614],
         [0.3181, 0.1564, 0.7224],
         ...,
         [0.0393, 0.4328, 0.2060],
         [0.8600, 0.0175, 0.5390],
         [0.9020, 0.7160, 0.3774]],

        [[0.8597, 0.0564, 0.6195],
         [0.5216, 0.6243, 0.8060],
         [0.9169, 0.4295, 0.0567],
         ...,
         [0.3150, 0.0344, 0.9619],
         [0.3948, 0.7845, 0.7585],
         [0.5184, 0.0386, 0.9673]],

        [[0.5888, 0.6581, 0.5662],
         [0.0925, 0.5569, 0.4766],
         [0.8783, 0.8551, 0.1835],
         ...,
         [0.1228, 0.6184, 0.7083],
         [0.2303, 0.0947, 0.5218],
         [0.6559, 0.6002, 0.0633]],

        ...,

        [[0.0732, 0.1898, 0.3147],
         [0.8924, 0.3418, 0.6193],
         [0.0120, 0.9068, 0.8565],
         ...,
         [0.4495, 0.9065, 0.8893],
         [0.6363, 0.8560, 0.7064],
         [0.6599, 0.3002, 0.8790]],

        [[0.2662, 0.1812, 0.9981],
         [0.5675, 0.8088, 0.4890],
         [0.

In [21]:
import torch
img2=torch.rand(size=(1,64,64))
img

tensor([[[0.6316, 0.6970, 0.0470],
         [0.2652, 0.8844, 0.7614],
         [0.3181, 0.1564, 0.7224],
         ...,
         [0.0393, 0.4328, 0.2060],
         [0.8600, 0.0175, 0.5390],
         [0.9020, 0.7160, 0.3774]],

        [[0.8597, 0.0564, 0.6195],
         [0.5216, 0.6243, 0.8060],
         [0.9169, 0.4295, 0.0567],
         ...,
         [0.3150, 0.0344, 0.9619],
         [0.3948, 0.7845, 0.7585],
         [0.5184, 0.0386, 0.9673]],

        [[0.5888, 0.6581, 0.5662],
         [0.0925, 0.5569, 0.4766],
         [0.8783, 0.8551, 0.1835],
         ...,
         [0.1228, 0.6184, 0.7083],
         [0.2303, 0.0947, 0.5218],
         [0.6559, 0.6002, 0.0633]],

        ...,

        [[0.0732, 0.1898, 0.3147],
         [0.8924, 0.3418, 0.6193],
         [0.0120, 0.9068, 0.8565],
         ...,
         [0.4495, 0.9065, 0.8893],
         [0.6363, 0.8560, 0.7064],
         [0.6599, 0.3002, 0.8790]],

        [[0.2662, 0.1812, 0.9981],
         [0.5675, 0.8088, 0.4890],
         [0.

In [23]:
image3=torch.rand(size=(4,23,23))
image3

tensor([[[0.8105, 0.1047, 0.9653,  ..., 0.7306, 0.7051, 0.8421],
         [0.8819, 0.5054, 0.0858,  ..., 0.0340, 0.8952, 0.5267],
         [0.6004, 0.0594, 0.9149,  ..., 0.4913, 0.4030, 0.2273],
         ...,
         [0.3451, 0.3334, 0.0414,  ..., 0.3890, 0.1847, 0.6820],
         [0.0192, 0.9860, 0.9681,  ..., 0.2772, 0.2459, 0.6025],
         [0.1477, 0.9015, 0.5143,  ..., 0.6757, 0.6334, 0.1088]],

        [[0.4574, 0.3954, 0.8226,  ..., 0.1831, 0.7329, 0.8490],
         [0.6575, 0.0900, 0.7871,  ..., 0.6502, 0.7864, 0.2835],
         [0.9917, 0.6714, 0.0796,  ..., 0.0827, 0.7147, 0.4510],
         ...,
         [0.1636, 0.9106, 0.0388,  ..., 0.1098, 0.1726, 0.7026],
         [0.6994, 0.3537, 0.2736,  ..., 0.3065, 0.1483, 0.2060],
         [0.7596, 0.8895, 0.4333,  ..., 0.4163, 0.6564, 0.5427]],

        [[0.6766, 0.6475, 0.0659,  ..., 0.0182, 0.1842, 0.4724],
         [0.3289, 0.1308, 0.4138,  ..., 0.5550, 0.2920, 0.5839],
         [0.1283, 0.7950, 0.5287,  ..., 0.8495, 0.1881, 0.

In [27]:
#CREATING ZEROS AND ONE
import torch
tensoerz=torch.zeros(4,4)
tensoerz
tensoro=torch.ones(7,8)
tensoro

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])